#!/usr/bin/env bash
cd 
git clone https://github.com/Bubujka/bu.bin.git .bu.bin
echo >> ~/.bashrc
echo 'PATH=$PATH:$HOME/.bu.bin/bin' >> ~/.bashrc
echo '. ~/.bu.bin/alias' >> ~/.bashrc
PATH=$PATH:$HOME/.bu.bin/bin
